### ISSUE TITLE
Message: Operation on an invalid type

### ISSUE THREAD

**Issue by sreejithk2000** [Taritsyn/BundleTransformer#48]
I am getting this error when trying to bundle the following less file. I can reproduce this in BundleTransformer.Less v 1.10.0 and v 1.12.0

```less
@primary-grey-50: #b4bbc2;

.generate-shades(lighten(@primary-grey-50, 7%));

/*Code to generate the classes for nested section pipes using recursive approach.*/
.generate-shades(@color, @selector: ~'.nested', @index: 3) when (@index > 0) {
    @elem: @selector + ~'.nested';

    @{elem} {
        border-left: 3px solid @color;
    }

    .generate-shades(lighten(@color, 7%), @elem, @index - 1);
}
```

### Error
```
During translation of LESS code, readed from the file '/Styles/Common.less', to CSS code syntax error has occurred.
See more details:

Error type: Syntax
Message: Operation on an invalid type
File: /Styles/Common.less
Line number: 14
Source error:

Line 14: .generate-shades(lighten(@primary-grey-50, 7%));

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: BundleTransformer.Core.Translators.AssetTranslationException: During translation of LESS code, readed from the file '/Styles/Common.less', to CSS code syntax error has occurred.
See more details:

Error type: Syntax
Message: Operation on an invalid type
File: /Styles/Common.less
Line number: 14
Source error:

Line 14: .generate-shades(lighten(@primary-grey-50, 7%));
```

### Stack Trace
```
[AssetTranslationException: During translation of LESS code, readed from the file '/Styles/Common.less', to CSS code syntax error has occurred. 
See more details:

Error type: Syntax
Message: Operation on an invalid type
File: /Styles/Common.less
Line number: 14
Source error:

Line 14: .generate-shades(lighten(@primary-grey-50, 7%));

]
   BundleTransformer.Less.Translators.LessTranslator.InnerTranslate(IAsset asset, LessCompiler lessCompiler, Boolean enableNativeMinification) +451
   BundleTransformer.Less.Translators.LessTranslator.Translate(IAsset asset) +118
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.InnerTranslateAsset(String translatorName, IAsset asset, ITransformer transformer, Boolean isDebugMode) +135
   BundleTransformer.Less.HttpHandlers.LessAssetHandler.TranslateAsset(IAsset asset, ITransformer transformer, Boolean isDebugMode) +49
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessAsset(String assetVirtualPath, String bundleVirtualPath) +271
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.GetProcessedAssetContent(String assetVirtualPath, String bundleVirtualPath) +310
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessRequest(HttpContextBase context) +312

[HttpException (0x80004005): During translation of LESS code, readed from the file '/Styles/Common.less', to CSS code syntax error has occurred. 
See more details:

Error type: Syntax
Message: Operation on an invalid type
File: /Styles/Common.less
Line number: 14
Source error:

Line 14: .generate-shades(lighten(@primary-grey-50, 7%));

]
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessRequest(HttpContextBase context) +1310
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +872
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +94
```
